# Koneksi Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Port aplikasi
server.port=${PORT:8080}

# Aktifkan profile lokal saat development (HAPUS/COMMENT baris ini sebelum push ke GitHub)
#spring.profiles.active=local